### ISSUE TITLE
[Feat Req.] Tumblr Support? 

### ISSUE THREAD

**Issue by momoe** [Simon-Tesla/RaccoonyWebEx#17] opened 2018-06-02 19:43 UTC
I'm not sure how the extension could parse the tab opening part, but at least having the ability to parse the title into the file name and directory for download sorting would be immensly useful for another outlet where artists submit. 

Please consider, when you have time. 
P.S. I've almost completely migrated to using Raccoony, it's been the best replacement for FA Extender and IB_Downloader. I'm really cheering for you.

**Comment by Simon-Tesla** [comment] 2018-06-02 19:55
Thanks! I'm glad you find Raccoony useful n.n

Tumblr support is definitely something I'd like to add (along with twitter support), but it works differently enough from the art sites that Raccoony was designed around that I'd have to give some serious thought into how to make it work.
* Most interaction is done through the dashboard, which has no single post, and virtualizes the DOM so it's difficult to do an "open all in tabs" from there.
* Posts themselves can have several pieces of media in them.
* Since tumblr allows custom domains and highly customizable themes, scraping posts from an individual tumblog is more challenging.

My best inkling of how tumblr support might work is that instead of having an overlay for the entire page, tumblr and similar sites would have something that looks for posts in the DOM and attaches a bit of UI to them.

Another thought would be to add a "Save with Raccoony" context menu item for images/media. The nice thing about this route is that I could support *all* websites generically with that, and potentially allow for better operation for supported sites via plugins.

**Comment by momoe** [comment] 2018-06-03 23:51
Yes, tumblr is a different entity altogether. I would say even if the tab opening feature would be too difficult to implement. Also there's the matter that tumblr's habit of subtituting a 1280px image instead of the raw version, with a hashed naming structure. I wish you the best, but probably save this tumblr enhancement as a later milestone (as opposed to a more static site like Hentai-Foundry). Again, thanks for considering this.

**Comment by Simon-Tesla** [comment] 2018-08-26 03:01
Fixed in 1.2.1

**Closed by Simon-Tesla** 2018-08-26 03:01 UTC
Labels: enhancement, in progress
