### ISSUE TITLE
randomly not able to download post from hentai foundry

### ISSUE THREAD

**Issue by 99spooner** [Simon-Tesla/RaccoonyWebEx#93] opened 2021-04-30 09:00 UTC
**Describe the bug**
when i go onto hentai foundry (hf) and go onto a post the raccoony icon wont show up in corner and i cant use keyboard shortcuts, what's weird is that its not happening on all the post as some will show the icon and i cant download, for example on [this page](https://www.hentai-foundry.com/pictures/user/Atya) out of all the post on it im only to download 2 of them ([this](https://www.hentai-foundry.com/pictures/user/Atya/849562/Beach-Queen-TyrAhnee-1) one & [this](https://www.hentai-foundry.com/pictures/user/Atya/849674/Beach-Queen-TyrAhnee-1-No-Text) one). my only guess  is that the two that do work have a lower maturity rating then the others and raccoony cant detect more mature ones for some reason but i colud be wrong its just a guess

**To Reproduce**
1. Go to hentai-foundry.com
2. Click on any post, it may take a few tries to find one with the problem
3. raccoony icon wont show up 

**Expected behavior**
i expect to go onto any post on HF and be able to download it either through the the download button or by the keyboard shortcut

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: google chrome
 - Version of Browser: 89.0.4389.128
 - Version of Raccoony:1.2.4

**Additional context**
- no matter what i do refresh page, open in different window, the icon wont show up

**Comment by Simon-Tesla** [comment] 2021-05-02 05:17
Repros on FF and Chrome on about half of the images in the gallery after doing an open-all-in-tabs. I haven't investigated the root cause, but Raccoony shows up for me for more than just the two images referenced above, but still not all of them. I'm not logged in when attempting to repro which may affect things as well.

**Comment by 99spooner** [comment] 2021-05-08 07:34
just wanna say i was logged in when only the 2 pages showed the icon,

**Comment by Eupeptic1** [comment] 2021-05-17 05:47
Can repro for some images in Firefox 78.10.0esr on Linux.

I added some logging statements to the HF plugin and went to the HF main page (not logged in) and hit open-in-tabs.  I got four images that didn't have the raccoon-head logo, out of a couple dozen total.

The four images that didn't work seem to be larger than HF's default viewable size.  All four are all the way to the left in the HF page and obviously run "out of frame" on the right edge.  The images that work are smaller and are centered on the HF page.

From a quick look, the URLs for the working images seem to start with `http://pictures.hentai-foundry.com`, and the rest of the URL conforms to what the plugin expects.  The URLs for the broken images seem to start with `http://thumbs.hentai-foundry.com/` and the rest of the URL just has some other ID numbers - not the author, submission ID, etc.

Investigation is ongoing.

**Comment by Eupeptic1** [comment] 2021-05-17 06:49
Once the image gets over a certain size, the main `img` element seems to give you a thumbnail on that `thumbs.hentai-foundry.com` server.  That `img` element has an `onClick` property that links to the full-size image on `pictures.hentai-foundry.com`.

A couple of sample images where the raccoon head fails to appear for me are below.  **These are NSFW!**  The links have been munged.

www.hentai-foundry dot com/pictures/user/onemienix/895583/Gawr-Gura-fanart
www.hentai-foundry dot com/pictures/user/InCase/904968/Velma-booba

By comparison, a sample image where the existing plugin works OK.  **NSFW**, munged.

www.hentai-foundry dot com/pictures/user/Araneesama/884192/Lulu-final-fantasy-x

I'm not quite sure how HF decides whether to "thumb" the image or not - if it's related to your current browser window size, or some hard-coded size.  I've tried it with my browser at about 1500x980, and full-screened at 1920x1080, but images that don't show the raccoon head at the smaller resolution also don't show it at the full-screen resolution.  This probably doesn't matter, though - I think we can reliably detect if we have a thumb by looking at the host name in the URL.

Proposed fix soon.

**Comment by Eupeptic1** [comment] 2021-05-17 07:01
Proposed fix here: https://gist.github.com/Eupeptic1/d8b5a8f726585694ebeb552a81f572c7

There are added logging statements throughout.

The main change is in `getImageDetails()`.  It now looks for the presence of `thumbs.hentai-foundry.com` in the image URL.  If found, it grabs the `onClick` attribute from the `img` and parses the full-sized image URL from it.  If not found, it proceeds as before.

The parsing depends on the Javascript in the onClick not changing much.  There may be a better way to do it.

The parsing also adds a fixed `http` protocol to the URL, since the string from the `onClick` lacks a protocol.  If some images are served over https, or if HF upgrades to https in the future, this will break.  Maybe a better idea would be to read whatever the current page protocol is, and use that.

I tested it against four images that used to be broken, and it DTRT for all four, including metadata.  I also tested it against one image that previously worked, and it still works, including metadata.

**Comment by Simon-Tesla** [comment] 2021-05-19 06:33
Thanks for looking into this. Life has been hectic for me lately, so I'll take a look when I'm able.

**Comment by Eupeptic1** [comment] 2021-07-02 03:52
I haven't been dogfooding this, because I don't use HF.  I also haven't re-tested it (for any changes at HF) since my initial proposal.

The main concern I still have about it is using the fixed `http` protocol to build a URL.  If it would be better to read the current document's protocol and use that instead, I can figure out how to do that, and retest.

**Comment by Simon-Tesla** [comment] 2021-09-06 02:38
Fix checked in

**Closed by Simon-Tesla** 2021-09-06 02:38 UTC
Labels: bug, investigation needed, hfoundry
